SET SERVEROUTPUT ON;

-- Author : Ionel Mihai Alexandru DAVAX DE
/*
 ======== Database creation area =========
 This area of the script is in charge with the database creation
 Constraints used:
    1. PK | 2. FK | 3. NOT NULL | 4. CHECK | 5. DEFAULT | 6. ALWAYS AS ... VIRTUAL| 7. CHECK pe JSON
    DEFAULT - daca valoarea nu este specificata la inserare, aceasta va fi default N (nu)
    ALWAYS - nu se poate seta valoarea manual
    VIRTUAL - valoarea este calculata la fiecare interogare si nu este stocata fizic
 !!!! Explicatii:
    1* as identity creaza o secventa interna si implicita,
        precum si un triger care este folosit atunci cand inserezi anumite randuri (nu mai trebuie facut manual)
    2* CLOB (Character large object) ne ajuta sa stocam texte foarte lungi (bun pentru fromat json)
*/
-- employees tabel creation:
CREATE TABLE employees (
    employeeID NUMBER GENERATED BY DEFAULT AS IDENTITY, -- explicatie 1*
    firstName VARCHAR2(50) NOT NULL,
    lastName VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    workingLocation VARCHAR2(10) NOT NULL,
    companyRole VARCHAR2(50) NOT NULL,
    hireDate DATE DEFAULT SYSDATE,
    PRIMARY KEY (employeeID)
);
-- projects table creation:
CREATE TABLE projects (
    projectID VARCHAR2(20),
    projectName VARCHAR2(100) NOT NULL,
    clientName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (projectID)
);
-- tasks table creation:
CREATE TABLE tasks (
    taskID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    taskName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (taskID)
);
-- timetypes table creation: (timetypes sunt cele de genu :Regular, OT...)
CREATE TABLE timeTypes (
    timeTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    timeTypeName VARCHAR2(50) UNIQUE NOT NULL,
    PRIMARY KEY (timeTypeID)
);
-- locations table creation:
CREATE TABLE locations (
    locationID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    locationName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (locationID)
);
-- contry for relocation table creation:
CREATE TABLE countries (
    countryID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    countryName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (countryID)
);
-- timesheets table creation:
-- This is the most important table!

CREATE TABLE timesheets (
    timesheetID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employeeID NUMBER NOT NULL,
    projectID VARCHAR2(20) NOT NULL,
    taskID NUMBER NOT NULL,
    timeTypeID NUMBER NOT NULL,
    -- Datele calendaristice de start si sfarsit al pontajului
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    -- ora de start si ora de finish al programului (in format 24h)
    startHour NUMBER(2) NOT NULL CHECK (startHour BETWEEN 0 AND 23), --Check constaing
    endHour NUMBER(2) NOT NULL CHECK (endHour BETWEEN 0 AND 23), --Check constraint 2
    -- cate ore au fost lucrate (generat automat ca diferenta dintre start-end)
    quantity NUMBER(4,2) GENERATED ALWAYS AS (endHour - startHour) VIRTUAL CHECK (quantity >= 0),
    -- campuri optionale (daca este cazul sunt completate, altfel null)
    locationID NUMBER,        -- pentru business trip
    relocatedCountryID NUMBER, -- pentru relocare (just in case)
    publicHolidayFlag CHAR(1) DEFAULT 'N' CHECK (publicHolidayFlag IN ('Y', 'N')), --daca se lucreaza in timpul unei sarbatori
    -- comentarii ale angajatilor in lecatura cu pontajul
    comments VARCHAR2(400),
    -- date semistructurate (JSON) : Aici putem stoca diferite date hidden (clientFeedback, toolsUsed, etc..)
    extraInfo CLOB CHECK (extraInfo IS JSON),   --2*
    --chei Pk si FK
    PRIMARY KEY (timesheetID),
    CONSTRAINT fk_employee FOREIGN KEY (employeeID) REFERENCES employees(employeeID),
    CONSTRAINT fk_project FOREIGN KEY (projectID) REFERENCES projects(projectID),
    CONSTRAINT fk_task FOREIGN KEY (taskID) REFERENCES tasks(taskID),
    CONSTRAINT fk_timeType FOREIGN KEY (timeTypeID) REFERENCES timeTypes(timeTypeID),
    CONSTRAINT fk_location FOREIGN KEY (locationID) REFERENCES locations(locationID),
    CONSTRAINT fk_country FOREIGN KEY (relocatedCountryID) REFERENCES countries(countryID)
);

/*
 ======== Index creation area =========
 This area of the script is in charge with index creation
 !!!! Explicatii:
    Indexii ne ajuta sa parcurgem mai repede setul de date pentru a gasi rezultatele
    Functioneaza ca un cuprins al unei carti, sar direct la ce ne intereseaza.
*/
-- index pentru stratHour pentru a vedea intrarile la o anumita ora
CREATE INDEX idx_timesheets_startHour ON timesheets(startHour);
-- index pe projectID pentru a sorta in functie de proiect direct
CREATE INDEX idx_timesheets_projectID ON timesheets(projectID);
-- index pe employeeID util cand vrem sa vedem toate pontarile unui angajat
CREATE INDEX idx_timesheets_employeeID ON timesheets(employeeID);
-- index pe timeTypeID util cand facem statistici de exeplu cate ore suplimentare au fost lucrate
CREATE INDEX idx_timesheets_timeTypeID ON timesheets(timeTypeID);
-- index compus pe startDate/endDate pentru rapoarte saptanale/lunare/anuale
CREATE INDEX idx_timesheets_date_range ON timesheets(startDate, endDate);

/*
 ======== Data population area =========
 This area of the script is in charge with data inseration
 !!!! Explicatii:
    Aici inseram date fictive generate cu ajutorul GPT in tabelele noastre
*/

INSERT INTO employees (firstName, lastName, email, workingLocation, companyRole)
VALUES ('Ana', 'Popescu', 'ana.popescu@endava.com', 'RO', 'Software Developer');
INSERT INTO employees (firstName, lastName, email, workingLocation, companyRole)
VALUES ('John', 'Smith', 'john.smith@endava.com', 'UK', 'Scrum Master');
INSERT INTO employees (firstName, lastName, email, workingLocation, companyRole)
VALUES ('Mihai', 'Ionescu', 'mihai.ionescu@endava.com', 'RO', 'QA Engineer');
INSERT INTO employees (firstName, lastName, email, workingLocation, companyRole)
VALUES ('Maria', 'Garcia', 'maria.garcia@endava.com', 'ES', 'Product Owner');
INSERT INTO employees (firstName, lastName, email, workingLocation, companyRole)
VALUES ('Ivan', 'Petrov', 'ivan.petrov@endava.com', 'BG', 'Software Developer');
COMMIT;

INSERT INTO projects (projectID, projectName, clientName)
VALUES ('BHD100VISA', 'Visa Integration', 'Visa');
INSERT INTO projects (projectID, projectName, clientName)
VALUES ('AMZ345DEL', 'Delivery Tracker', 'Amazon');
INSERT INTO projects (projectID, projectName, clientName)
VALUES ('GGL210MAP', 'Map Enhancer', 'Google');
INSERT INTO projects (projectID, projectName, clientName)
VALUES ('NTF900MKT', 'NFT Marketplace', 'OpenSea');
COMMIT;

INSERT INTO tasks (taskName) VALUES ('Development');
INSERT INTO tasks (taskName) VALUES ('Code Review');
INSERT INTO tasks (taskName) VALUES ('Testing');
INSERT INTO tasks (taskName) VALUES ('Documentation');
INSERT INTO tasks (taskName) VALUES ('Sprint Planning');
INSERT INTO tasks (taskName) VALUES ('Negotiations');
COMMIT;

INSERT INTO timeTypes (timeTypeName) VALUES ('Regular');
INSERT INTO timeTypes (timeTypeName) VALUES ('Overtime');
INSERT INTO timeTypes (timeTypeName) VALUES ('TOIL Overtime');
INSERT INTO timeTypes (timeTypeName) VALUES ('Extended Overtime');
INSERT INTO timeTypes (timeTypeName) VALUES ('Travel');
COMMIT;

INSERT INTO locations (locationName) VALUES ('London');
INSERT INTO locations (locationName) VALUES ('Bucharest');
INSERT INTO locations (locationName) VALUES ('Madrid');
INSERT INTO locations (locationName) VALUES ('Sofia');
INSERT INTO locations (locationName) VALUES ('New York');
COMMIT;

INSERT INTO countries (countryName) VALUES ('United Kingdom');
INSERT INTO countries (countryName) VALUES ('Romania');
INSERT INTO countries (countryName) VALUES ('Spain');
INSERT INTO countries (countryName) VALUES ('Bulgaria');
INSERT INTO countries (countryName) VALUES ('USA');
COMMIT;

-- !!!! Insertion into timesheets table (main table)
-- Ana Popescu - Regular+OT 
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (1, 'BHD100VISA', 1, 1,DATE '2025-06-03', DATE '2025-06-03', 9, 17,NULL, NULL, 'N',
    'Worked on backend services.','{"sprint":"Sprint 12", "jira":"END-1234"}'
);
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (1, 'BHD100VISA', 3, 2,DATE '2025-06-04', DATE '2025-06-04', 9, 18,NULL, NULL, 'N',
    'Executed integration tests.','{"tools":"Postman", "device":"Mac"}'
);
-- John Smith – Code review de urgenta in zi libera
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (2, 'AMZ345DEL', 2, 2,DATE '2025-06-03', DATE '2025-06-03', 10, 18,1, NULL, 'Y',
    'Reviewed code on holiday.','{"tools":"Visual Studio Code 2019", "status":"urgent"}'
);
-- Mihai Ionescu – Regular + OT / documentation
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (3, 'GGL210MAP', 1, 1,DATE '2025-06-04', DATE '2025-06-04', 8, 17,NULL, 5, 'N',
    'Normal testing tasks.','{"device":"Android", "tools":"Android Studio", "hardware":"Samsung S20"}'
);
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (3, 'GGL210MAP', 4, 2,DATE '2025-06-05', DATE '2025-06-05', 9, 19,NULL, 5, 'N',
    'Wrote user documentation.','{"language":"EN"}'
);
-- Maria Garcia – Product Owner Regular
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (4, 'NTF900MKT', 5, 1,DATE '2025-06-03', DATE '2025-06-03', 10, 18,NULL, NULL, 'N',
    'Product grooming session.','{"feature":"wallet"}'
);
-- Ivan Petrov – Business trip new york
INSERT INTO timesheets (employeeID, projectID, taskID, timeTypeID,startDate, endDate, startHour, endHour,
    locationID, relocatedCountryID, publicHolidayFlag,comments, extraInfo)
VALUES (5, 'BHD100VISA', 6, 4,DATE '2025-06-06', DATE '2025-06-06', 9, 20,5, 5, 'N',
    'Met client in New York.','{"travelMode":"flight"}'
);
COMMIT;
--Select * from timesheets;
/*
 ======== View creation area =========
 This area of the script is in charge with view creation
 !!!! Explicatii:
   View - tabel virtual care nu stocheaza date, doar defineste o interogare reutilizabila
   Materialized view - tip special de view care salveaza datele fizic in baza de date, ca o copie a unui select.
                      * este util deoarece se actualizeaza automat si poate interoga foarte rapid in cazul rapoartelor lente si costisitoare

    Am folosit Join, Group BY,SUM, LEFT JOIN
*/

-- materialized view - cate ore sunt lucrate te toti angajatii in functie de tipul de timp pontat.
CREATE MATERIALIZED VIEW mview_ore_timetypes
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT 
    tt.timeTypeName,
    SUM(t.quantity) AS totalHours
FROM timesheets t
JOIN timeTypes tt ON t.timeTypeID = tt.timeTypeID
GROUP BY tt.timeTypeName;
COMMIT;

-- materialized view pentru a vedea totalul orelor lucrate pe saptaman per angajat, astfel obtinem o
-- imagine generala asupra volumului de munca depus de fiecare.
CREATE MATERIALIZED VIEW mview_lucru_saptamanal_anagajati
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT
    e.employeeID,
    e.firstName || ' ' || e.lastName AS employeeName,
    TRUNC(t.startDate, 'IW') AS week_start_date,
    SUM(t.quantity) AS total_hours
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
GROUP BY e.employeeID, e.firstName, e.lastName, TRUNC(t.startDate, 'IW'); -- pentru a incepe saptamana luni, nu duminica
COMMIT;

--view -  cate ore a lucrat fiecare angajat pe proiect
CREATE OR REPLACE VIEW view_ore_per_angajat_per_proiect AS
SELECT 
    e.firstName || ' ' || e.lastName AS employeeName,
    p.projectName,
    SUM(t.quantity) AS totalHours
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
JOIN projects p ON t.projectID = p.projectID
GROUP BY e.firstName, e.lastName, p.projectName;
COMMIT;

-- view detaliat pe post de dashboard deoarece combina toate tabelele
CREATE OR REPLACE VIEW view_dashboard_detaliat AS
SELECT
    t.timesheetID,
    e.firstName || ' ' || e.lastName AS employeeName,
    p.projectName,
    tk.taskName,
    tt.timeTypeName,
    TO_CHAR(t.startDate, 'DD-MM-YYYY') AS workDay,
    t.startHour,
    t.endHour,
    t.quantity,
    l.locationName,
    c.countryName AS relocatedCountry,
    t.publicHolidayFlag,
    t.comments,
    t.extraInfo
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
JOIN projects p ON t.projectID = p.projectID
JOIN tasks tk ON t.taskID = tk.taskID
JOIN timeTypes tt ON t.timeTypeID = tt.timeTypeID
LEFT JOIN locations l ON t.locationID = l.locationID
LEFT JOIN countries c ON t.relocatedCountryID = c.countryID;
COMMIT;

-- view care arata orele suplimentare lucrate de fiecare angajat, grupate pe tip de ora suplimentara.
CREATE OR REPLACE VIEW view_anagjati_overtime AS
SELECT
    e.firstName || ' ' || e.lastName AS employeeName,
    tt.timeTypeName,
    SUM(t.quantity) AS overtimeHours
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
JOIN timeTypes tt ON t.timeTypeID = tt.timeTypeID
WHERE tt.timeTypeName IN ('Overtime', 'TOIL Overtime', 'Extended Overtime') -- permite numai cele de tip overtime
GROUP BY e.firstName, e.lastName, tt.timeTypeName;
COMMIT;

-- view care arata angajatii care au fost relocati sau au calatorit in scop de business
CREATE OR REPLACE VIEW view_angajati_relocati_businesTrip AS
SELECT
    e.firstName || ' ' || e.lastName AS employeeName,
    l.locationName AS travelLocation,
    c.countryName AS relocatedTo,
    t.startDate,
    t.projectID
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
LEFT JOIN locations l ON t.locationID = l.locationID
LEFT JOIN countries c ON t.relocatedCountryID = c.countryID
WHERE t.locationID IS NOT NULL OR t.relocatedCountryID IS NOT NULL;
COMMIT;


/*
 ========SELECT STATEMETN AREA =========
 
 !! LEFT JOINS si GROUP BY au fost folosite si in view-uri.
 Am folosit RANK(), AVG() ...OVER(),  ROUND(), PARTITION
*/

-- SELECT din VIEW pentru a vedea orele lucrate de fiecare angajat in cadrul proiectelor lor 
SELECT * FROM view_ore_per_angajat_per_proiect;

-- Select din VIEW pentru a vedea un "dashboard" detaliat al timesheetului - practic vedem timesheetul dar completat
-- cu datele din celelalte tabele deoarece am dat join si putem afisa valorile exact, nu numai IDs
SELECT * FROM view_dashboard_detaliat;
--Select * from timesheets;

-- Select din vview pentru a vedea numarul de ore de overtime al fiecarui angajat, in functie de tipul de overtime
SELECT * FROM view_anagjati_overtime;

-- Select din view pentru a vedeaangajatii care muncesc fie fiind relocati fie au calatorit in scop de business.
SELECT * FROM view_angajati_relocati_businesTrip;

-- SELECT din MATERIALIZED VIEW pentru a vedea totalul orelor lucrate pe fiecare categorie de timpv(Regular, ot ...)
SELECT * FROM mview_ore_timetypes;

-- SELECT din MATERIALIZED VIEW pentru a vedea volumul de munca depus saptamanal de fiecare angajat.
SELECT * FROM mview_lucru_saptamanal_anagajati;


-- SELECT care listeaza toti angajatii si pontarile lor daca exitsa
-- LEFT JOIN: include toti angajatii, chiar si cei fara pontaj daca sunt (coloanele lor vor fi null)
SELECT
    e.employeeID,
    e.firstName || ' ' || e.lastName AS employeeName,
    t.startDate,
    t.projectID,
    t.quantity
FROM employees e
LEFT JOIN timesheets t ON e.employeeID = t.employeeID
ORDER BY e.employeeID, t.startDate;

-- SELECT care compara media orelor lucrate zilnic cu valorile efective lucrate in fiecare zi
-- Pentru un dataset mare, nu este o functie utila deoarece returneaza foarte multe rezultate
/*Explicatie:
 ROUND(AVG(t.quantity) OVER (PARTITION BY t.employeeID), 2) AS avg_quantity_per_employee
        AVG -> calculeaza media valorilor din quantity
        OVER (PARTITION BY ...) -> calculeaza media separat pentru fiecare angajat, grupare pe employeeID
                                -> diferenta fara de groupBY : nu reduce randurile la o singura linie, pastreaza fiecare rand sia dauga o col calculata
        ROUND(..,2) -> rotunjeste rez la 2 zecimale
*/
SELECT
    t.timesheetID,
    e.firstName || ' ' || e.lastName AS employeeName,
    t.startDate,
    t.quantity,
    ROUND(AVG(t.quantity) OVER (PARTITION BY t.employeeID), 2) AS avg_quantity_per_employee  --f analitică: media orelor pe angajat
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
ORDER BY e.employeeID, t.startDate;


-- SELECT pentru clasificarea zilelor lucrate în functie de orele lucrate
 -- in functie de angajat, in ordine descrescatoare, cu atributul rank
 -- se poate astfel vedea zilele cu cele mai multe ore in ordine descrescatoare pentru fiecare angajat
SELECT
    e.firstName || ' ' || e.lastName AS employeeName,
    t.startDate,
    t.quantity,
    RANK() OVER (PARTITION BY t.employeeID ORDER BY t.quantity DESC) AS rank_by_quantity  --clasifica in func de nr de ore lucrate
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
ORDER BY employeeName, rank_by_quantity;

-- SELECT pt ore totale lucrate pe fiecare proiect, impartit pe tip de ore (Regular,ot etc.)
-- grupat dupa proiect si tipul de timp lucrat
SELECT
    p.projectName,
    tt.timeTypeName,
    SUM(t.quantity) AS total_hours
FROM timesheets t
JOIN projects p ON t.projectID = p.projectID
JOIN timeTypes tt ON t.timeTypeID = tt.timeTypeID
GROUP BY p.projectName, tt.timeTypeName
ORDER BY p.projectName, tt.timeTypeName;


/*   BONUS : EXPLAIN PLAN  */

EXPLAIN PLAN FOR
SELECT
    e.firstName || ' ' || e.lastName AS employeeName,
    t.startDate,
    t.quantity,
    RANK() OVER (PARTITION BY t.employeeID ORDER BY t.quantity DESC) AS rank_by_quantity
FROM timesheets t
JOIN employees e ON t.employeeID = e.employeeID
ORDER BY employeeName, rank_by_quantity;


SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
