/*
    This script is in charge with overall project structure - eg. tables.
    Target: Create a complex galaxy(star) schema for DAVAX employees, taking into consideration all the information avaiable.
    
    I will create multiple dimension tables and fact tables
    Dimension tables:
        - dim_employee      : employees info
        - dim_date          : this is a calendar table, needed to group events by dates
        - dim_time          : **optional table used for splitting day time (Eg for morning/afternoon meetings
        - dim_absence_type  : type of absence (eg. University Exam, Sick Day, Holiday, etc..)
        - dim_project       : **optional project info
    
    Fact tables:
        - fact_meeting_participation    : one row per employee per meeting : contains time joines, duration, etc
        - fact absences                 : one row per absence event per employee
        - fact_project_work             : time spent per employee per project
        
    LOGIC!
        all fact tables are linked to the dim_employee on employee_id
        all events are connected to dim_date
        the absences are linked to dim_absence_type
        
    SCHEMA
                  dim_employee   
                        |
      +-----------------+------------------+
      |                 |                  |
| fact_meeting|   | fact_absences |   | fact_projects  |  
      |                  |                  |    
   | dim_date|      | dim_absence|     | dim_project|
  

*/

-- ============== CREATION ==============

CREATE TABLE dim_employee (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    department VARCHAR2(50),
    position VARCHAR2(50)
);

CREATE TABLE dim_date (
    date_id DATE PRIMARY KEY,
    day_of_week VARCHAR2(10),
    week_number NUMBER,
    month_number NUMBER,
    month_name VARCHAR2(15),
    quarter VARCHAR2(2),
    year NUMBER
);

CREATE TABLE dim_absence_type (
    absence_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR2(50),
    description VARCHAR2(255)
);

CREATE TABLE dim_project (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR2(100),
    project_owner VARCHAR2(100),
    client_name VARCHAR2(100)
);

CREATE TABLE fact_meeting_participation (
    meeting_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    date_id DATE,
    join_time TIMESTAMP,
    leave_time TIMESTAMP,
    duration_minutes NUMBER,
    role VARCHAR2(30),

    CONSTRAINT fk_meeting_employee
        FOREIGN KEY (employee_id) REFERENCES dim_employee(employee_id),
    CONSTRAINT fk_meeting_date
        FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
);


CREATE TABLE fact_absences (
    absence_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    date_id DATE,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    absence_type_id NUMBER,
    organizer VARCHAR2(100),

    CONSTRAINT fk_absence_employee
        FOREIGN KEY (employee_id) REFERENCES dim_employee(employee_id),
    CONSTRAINT fk_absence_date
        FOREIGN KEY (date_id) REFERENCES dim_date(date_id),
    CONSTRAINT fk_absence_type
        FOREIGN KEY (absence_type_id) REFERENCES dim_absence_type(absence_type_id)
);

CREATE TABLE fact_project_work (
    work_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER,
    project_id NUMBER,
    date_id DATE,
    hours_worked NUMBER(5,2),

    CONSTRAINT fk_project_work_employee
        FOREIGN KEY (employee_id) REFERENCES dim_employee(employee_id),
    CONSTRAINT fk_project_work_project
        FOREIGN KEY (project_id) REFERENCES dim_project(project_id),
    CONSTRAINT fk_project_work_date
        FOREIGN KEY (date_id) REFERENCES dim_date(date_id)
);





