/*
    This script is in charge with overall project structure - eg. tables.
    Target: Create a complex galaxy(star) schema for DAVAX employees, taking into consideration all the information avaiable.
    
    I will create multiple dimension tables and fact tables
*/

-- ============== CREATION ==============

CREATE TABLE dim_employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    department VARCHAR2(50),
    role VARCHAR2(50)
);

CREATE TABLE dim_dates (
    date_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year NUMBER,
    month NUMBER,
    quarter NUMBER,
    day NUMBER 
);

CREATE TABLE dim_meet_role (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(50)
);

CREATE TABLE dim_meetings(
    meet_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER, 
    employee_name VARCHAR2(100),
    first_join TIMESTAMP,  -- TO_TIMESTAMP('6/24/25, 1:54:40 PM', 'MM/DD/YY, HH:MI:SS PM') 
    last_leave TIMESTAMP,
    meeting_time VARCHAR2(30),
    email VARCHAR2(100),

    CONSTRAINT fk_meeting_role
        FOREIGN KEY (role_id) REFERENCES role_meet(role_id)
);

CREATE TABLE dim_absences(
    absence_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR2(50),
    start_date DATE,
    start_time  TIMESTAMP,
    end_date DATE,
    end_time    TIMESTAMP,
    all_day_event   BOOLEAN,
    meeting_organizer   VARCHAR2(100),
    description     VARCHAR2(200),
    location    VARCHAR2(50)
);

CREATE TABLE fact_timesheets(
    employee_id NUMBER NOT NULL,
    meet_id NUMBER NOT NULL,
    absence_id NUMBER NOT NULL,
    date_id NUMBER NOT NULL,

    total_time_in_meetings  VARCHAR2(50),
    total_number_absences   NUMBER,
    total_absence_time  VARCHAR2(50),

    CONSTRAINT fk_timesheet_employees
        FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id),
    CONSTRAINT fk_timesheet_employees
        FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)
);