import oracledb

from utils.utils import Utils

connection = oracledb.connect(
    user='dan',
    password='davax_pass',
    dsn='localhost:1521/XEPDB1'
)

# define the cursor
cursor = connection.cursor()

# get all the table names from the database
cursor.execute('SELECT table_name FROM user_tables')

# convert the table names into a list
table_names = [row[0] for row in cursor.fetchall()]

for name in table_names:
    try:
        cursor.execute(Utils.drop_table(name))
    except oracledb.DatabaseError as e:
        if 'ORA-00942' in str(e):  # table does not exist
            continue
        else:
            break

# create tables
tables = [
    {
        "name": "dim_employees",
        "columns": [
            ("employee_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("first_name", "VARCHAR2(50)"),
            ("last_name", "VARCHAR2(50)"),
            ("email", "VARCHAR2(100)")
        ]
    },
    {
        "name": "dim_dates",
        "columns": [
            ("date_id", "DATE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("year", "NUMBER"),
            ("month", "NUMBER"),
            ("quarter", "NUMBER"),
            ("day", "NUMBER")
        ]
    },
    {
        "name": "dim_projects",
        "columns": [
            ("project_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("project_name", "VARCHAR2(20) DEFAULT 'DavaX'")
        ]
    },
    {
        "name": "dim_events",
        "columns": [
            ("event_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("event_name", "VARCHAR2(50)"),
            ("event_type", "VARCHAR2(50)"),  # e.g. Meeting, AL = Annual Leave, SL = Sick Leave, UL = University Leave
            ("event_organizer", "VARCHAR2(50)")
        ]
    },
    {
        "name": "fact_timesheets",
        "columns": [
            ("timesheet_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("employee_id", "NUMBER NOT NULL"),
            ("event_id", "NUMBER NOT NULL"),
            ("date_id", "DATE NOT NULL"),
            ("project_id", "VARCHAR2(50)"),
            ("quantity", "NUMBER NOT NULL")
        ],
        "constraints": [
            "CONSTRAINT uq_employee_meet_absence_date UNIQUE (employee_id, event_id, date_id, project_id)",

            "CONSTRAINT fk_timesheet_employees FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)",
            "CONSTRAINT fk_timesheet_events FOREIGN KEY (event_id) REFERENCES dim_events(event_id)",
            "CONSTRAINT fk_timesheet_dates FOREIGN KEY (date_id) REFERENCES dim_dates(date_id)"
            "CONSTRAINT fk_timesheet_projects FOREIGN KEY (project_id) REFERENCES dim_projects(project_id)"
        ]

        # cum arata inregistrarile in fact_timesheets'
        # employee_id | event_id |  date_id          | project_id | quantity
        # 1           | 1        | 30-06-2025        | 1          | 8
    }
]

# execute all table creation statements
for table in tables:
    cursor.execute(Utils.create_table(table_name=table.get('name'),
                                      columns=table.get('columns'),
                                      constraints=table.get('constraints')))

# commit the changes
connection.commit()

# print statement to verify if correct
print("Tables created successfully.")


# TODO Alex: Create source tables for every table in the database, populezi cu GPT tabelul de timesheets (id, nume, data, project_name, qty)
# TODO: Populate the dimension tables with data from the source tables
# TODO: Populate dim dates table
# TODO: populate the fact table with data from the dimension tables