import oracledb

from utils.utils import Utils

connection = oracledb.connect(
    user='dan',
    password='davax_pass',
    dsn='localhost:1521/XEPDB1'
)

# define the cursor
cursor = connection.cursor()

# get all the table names from the database
cursor.execute('SELECT table_name FROM user_tables')

# convert the table names into a list
table_names = [row[0] for row in cursor.fetchall()]

for name in table_names:
    try:
        cursor.execute(Utils.drop_table(name))
    except oracledb.DatabaseError as e:
        if 'ORA-00942' in str(e): # table does not exist
            continue
        else:
            break

# create tables
tables = [
    {
        "name": "dim_employees",
        "columns": [
            ("employee_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("first_name", "VARCHAR2(50)"),
            ("last_name", "VARCHAR2(50)"),
            ("email", "VARCHAR2(100)"),
            ("department", "VARCHAR2(50)"),
            ("role", "VARCHAR2(50)"),
            ("line_manager", "VARCHAR2(50)")
        ]
    },
    {
        "name": "dim_dates",
        "columns": [
            ("date_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("year", "NUMBER"),
            ("month", "NUMBER"),
            ("quarter", "NUMBER"),
            ("day", "NUMBER")
        ]
    },
    {
        "name": "dim_meet_role",
        "columns": [
            ("role_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("role_type", "VARCHAR2(50)")
        ]
    },
    {
        "name": "dim_meetings",
        "columns": [
            ("meet_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("role_id", "NUMBER"),
            ("employee_name", "VARCHAR2(100)"),
            ("first_join", "TIMESTAMP"),
            ("last_leave", "TIMESTAMP"),
            ("meeting_time", "VARCHAR2(30)"),
            ("email", "VARCHAR2(100)"),
            ("employee_id", "NUMBER NOT NULL")
        ],
        "constraints": [
            "CONSTRAINT fk_meeting_role FOREIGN KEY (role_id) REFERENCES dim_meet_role(role_id)",
            "CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)"
        ]
    },
    {
        "name": "dim_absences",
        "columns": [
            ("absence_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("subject", "VARCHAR2(50)"),
            ("start_date", "DATE"),
            ("start_time", "TIMESTAMP"),
            ("end_date", "DATE"),
            ("end_time", "TIMESTAMP"),
            ("all_day_event", "CHAR(1) CHECK (all_day_event IN ('Y', 'N'))"),
            ("meeting_organizer", "VARCHAR2(100)"),
            ("description", "VARCHAR2(200)"),
            ("location", "VARCHAR2(50)")
        ]
    },
    {
        "name": "fact_timesheets",
        "columns": [
            ("timesheet_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("employee_id", "NUMBER NOT NULL"),
            ("meet_id", "NUMBER NOT NULL"),
            ("absence_id", "NUMBER NOT NULL"),
            ("date_id", "NUMBER NOT NULL"),
            ("total_time_in_meetings", "NUMBER"),
            ("total_number_absences", "NUMBER"),
            ("total_absence_time", "VARCHAR2(50)")
        ],
        "constraints": [
            "CONSTRAINT uq_employee_meet_absence_date UNIQUE (employee_id, meet_id, absence_id, date_id)",
            "CONSTRAINT fk_timesheet_employees FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)",
            "CONSTRAINT fk_timesheet_meetings FOREIGN KEY (meet_id) REFERENCES dim_meetings(meet_id)",
            "CONSTRAINT fk_timesheet_absences FOREIGN KEY (absence_id) REFERENCES dim_absences(absence_id)",
            "CONSTRAINT fk_timesheet_dates FOREIGN KEY (date_id) REFERENCES dim_dates(date_id)"
        ]
    },
    {
        "name": "dim_timesheets",
        "columns": [
            ("timesheet_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("employee_id", "NUMBER NOT NULL"),
            ("project", "VARCHAR2(20) NOT NULL"),
            ("task", "VARCHAR2(20) NOT NULL"),
            ("time_type", "VARCHAR2(20) NOT NULL"),
            ("start_date", "DATE NOT NULL"),
            ("end_date", "DATE NOT NULL"),
            ("start_hour", "NUMBER(2) NOT NULL CHECK (start_hour BETWEEN 0 AND 23)"),
            ("end_hour", "NUMBER(2) NOT NULL CHECK (end_hour BETWEEN 0 AND 23)"),
            ("location", "VARCHAR2(20)")
        ],
        "constraints": [
            "CONSTRAINT fk_employee_dim FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)"
        ]
    }
]

# execute all table creation statements
for table in tables:
    cursor.execute(Utils.create_table(table_name=table.get('name'), columns=table.get('columns'), constraints=table.get('constraints')))

# commit the changes
connection.commit()

# print statement to verify if correct
print("Tables created successfully.")



# TODO: Take the email from teams meeting and insert it into dim_employees
# TODO: Take line manager from teams and link him with the office
# TODO: Later check if we can extract line manager and department from teams dynamically
# TODO: Take the department from teams dynamically

# TODO: Darius to make the inserts; Split the full name into first name and last name in dim_employees, Split location according to '-' into country, city, office location
# TODO: Alex Take the email from teams meeting and insert it into dim_employees; Take line manager from teams and link him with the office
# TODO: Dan Later check if we can extract line manager and department from teams dynamically Take the department from teams dynamically