import oracledb

from utils.insert_values_into_tables import InsertValuesIntoTables
from utils.utils import Utils


class DimTables:
    """
    This class is responsible for creating the dimension tables in the Oracle database.
    It includes methods to drop existing tables, create new ones, and populate the dim_dates table.
    """
    def __init__(self, connection):
        """
        Initializes the DimTables class with a database connection.

        :param connection: An active Oracle database connection."""
        self.connection = connection

    def create_tables(self):
        """
        Creates the dimension tables in the database.

        :param cursor: An Oracle database cursor to execute SQL commands.
        """
        cursor = self.connection.cursor()
        # get all the table names from the database
        cursor.execute('SELECT table_name FROM user_tables')

        # convert the table names into a list
        table_names = [row[0] for row in cursor.fetchall()]

        for name in table_names:
            try:
                cursor.execute(Utils.drop_table(name))
            except oracledb.DatabaseError as e:
                if 'ORA-00942' in str(e):  # table does not exist
                    continue
                else:
                    break

        # create dim_tables
        dim_tables = [
            {
                "name": "dim_employees",
                "columns": [
                    ("employee_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                    ("first_name", "VARCHAR2(50)"),
                    ("last_name", "VARCHAR2(50)"),
                    ("email", "VARCHAR2(100)")
                ]
            },
            {
                "name": "dim_dates",
                "columns": [
                    ("date_id", "DATE PRIMARY KEY"),
                    ("year", "NUMBER"),
                    ("month", "NUMBER"),
                    ("quarter", "NUMBER"),
                    ("day", "NUMBER")
                ]
            },
            {
                "name": "dim_projects",
                "columns": [
                    ("project_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                    ("project_name", "VARCHAR2(20) DEFAULT 'DavaX'")
                ]
            },
            {
                "name": "dim_events",
                "columns": [
                    ("event_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                    ("event_date", "DATE NOT NULL"),
                    ("event_name", "VARCHAR2(50)"),
                    ("event_type", "VARCHAR2(50)")  # e.g. Meeting, AL = Annual Leave, SL = Sick Leave, UL = University Leave
                ]
            },
            {
                "name": "fact_timesheets",
                "columns": [
                    ("timesheet_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                    ("employee_id", "NUMBER NOT NULL"),
                    ("event_id", "NUMBER NOT NULL"),
                    ("date_id", "DATE NOT NULL"),
                    ("project_id", "NUMBER NOT NULL"),
                    ("quantity", "NUMBER NOT NULL")
                ],
                "constraints": [
                    "CONSTRAINT uq_employee_meet_absence_date UNIQUE (employee_id, event_id, date_id, project_id)",

                    "CONSTRAINT fk_timesheet_employees FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)",
                    "CONSTRAINT fk_timesheet_events FOREIGN KEY (event_id) REFERENCES dim_events(event_id)",
                    "CONSTRAINT fk_timesheet_dates FOREIGN KEY (date_id) REFERENCES dim_dates(date_id)",
                    "CONSTRAINT fk_timesheet_projects FOREIGN KEY (project_id) REFERENCES dim_projects(project_id)"
                ]
            }
        ]

        # execute all table creation statements
        for table in dim_tables:
            cursor.execute(Utils.create_table(table_name=table.get('name'),
                                              columns=table.get('columns'),
                                              constraints=table.get('constraints')))

        # populate the dim_dates table
        dim_date_values = InsertValuesIntoTables.populate_dim_date_table()
        insert_dim_date_statement = Utils.insert_values_into_tables(
            table_name='dim_dates',
            columns=Utils.get_column_names(cursor, 'dim_dates')
        )

        # execute the insert statement for dim_dates
        cursor.executemany(insert_dim_date_statement, dim_date_values)

        # commit the changes
        self.connection.commit()

        # print statement to verify if correct
        print("Dim_Tables created successfully.")
