from utils.insert_values_into_tables import InsertValuesIntoTables
from utils.utils import Utils


class SourceTables:
    """
    This class is responsible for creating the source tables in the Oracle database.
    It includes methods to drop existing tables, create new ones
    """
    def __init__(self, connection):
        """
        Initializes the SourceTables class with a database connection.

        :param connection: An active Oracle database connection."""
        self.connection = connection

    def create_tables(self):
        """
        Creates the dimension tables in the database.

        :param cursor: An Oracle database cursor to execute SQL commands.
        """
        cursor = self.connection.cursor()

        source_tables = [
                {
                    "name": "src_timesheet_pontaj",
                    "columns": [
                            ("pontaj_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                            ("first_name", "VARCHAR2(50)"),
                            ("last_name", "VARCHAR2(50)"),
                            ("email", "VARCHAR2(100)"),
                            ("project_name", "VARCHAR(100)"),
                            ("pontaj_date", "DATE"),
                            ("quantity", "NUMBER")
                        ]
                },
                {
                    "name": "src_timesheet_absences",
                    "columns": [
                        ("absence_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                        ("first_name", "VARCHAR2(50)"),
                        ("last_name", "VARCHAR2(50)"),
                        ("email", "VARCHAR2(100)"),
                        ("absence_type", "VARCHAR(10)"),
                        ("absence_date", "DATE"),
                        ("quantity", "NUMBER")
                        ]
                },
                {
                    "name": "src_confluence_absences",
                    "columns": [
                        ("absence_id", "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
                        ("last_name", "VARCHAR2(50)"),
                        ("first_name", "VARCHAR2(50)"),
                        ("absence_type", "VARCHAR2(20)"),
                        ("start_time", "TIMESTAMP"),
                        ("end_time", "TIMESTAMP"),
                        ("all_day_event", "VARCHAR2(50)"),
                        ("quantity", "NUMBER")
                    ]
                },
                {
                    "name": "src_meetings",
                    "columns": [
                        ("meeting_id", "NUMBER"),
                        ("meeting_title", "VARCHAR2(50)"),
                        ("meeting_date", "DATE"),
                        ("first_name", "VARCHAR2(50)"),
                        ("last_name", "VARCHAR2(50)"),
                        ("email", "VARCHAR2(100)"),
                        ("quantity", "NUMBER(3, 2)")
                    ]
                }
        ]

        # execute all table creation statements
        for table in source_tables:
            cursor.execute(Utils.create_table(table_name=table.get('name'),
                                              columns=table.get('columns'),
                                              constraints=table.get('constraints')))
            
        print("Source tables created successfully.")

        InsertValuesIntoTables.insert_values_into_source_tables(cursor)

        # commit the changes
        self.connection.commit()