/*
    This script is in charge with overall project structure
    Target: Create a complex star schema for DAVAX employees, taking into consideration all the information available.
*/

-- ============== CREATION ==============

CREATE TABLE dim_employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    department VARCHAR2(50),
    role VARCHAR2(50),
    grade VARCHAR2(50),
    line_manager VARCHAR2(50),
    department VARCHAR2(50)
);

CREATE TABLE dim_dates (
    date_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year NUMBER,
    month NUMBER,
    quarter NUMBER,
    day NUMBER 
);

CREATE TABLE dim_meet_role (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(50)
);

CREATE TABLE dim_meetings(
    meet_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id NUMBER, 
    employee_name VARCHAR2(100),
    first_join TIMESTAMP,  -- TO_TIMESTAMP('6/24/25, 1:54:40 PM', 'MM/DD/YY, HH:MI:SS PM') 
    last_leave TIMESTAMP,
    meeting_time VARCHAR2(30),
    email VARCHAR2(100),
    employee_id NUMBER NOT NULL,

    CONSTRAINT fk_meeting_role
        FOREIGN KEY (role_id) REFERENCES dim_meet_role(role_id),
    CONSTRAINT fk_employee
        FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id)
);

CREATE TABLE dim_absences(
    absence_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR2(50),
    start_date DATE,
    start_time  TIMESTAMP,
    end_date DATE,
    end_time    TIMESTAMP,
    all_day_event   BOOLEAN,
    meeting_organizer   VARCHAR2(100),
    description     VARCHAR2(200),
    location    VARCHAR2(50)
);

CREATE TABLE fact_timesheets(
    timesheet_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    meet_id NUMBER NOT NULL,
    absence_id NUMBER NOT NULL,
    date_id NUMBER NOT NULL,

    total_time_in_meetings  NUMBER,   -- time in minutes
    total_number_absences   NUMBER,
    total_absence_time  VARCHAR2(50),

    CONSTRAINT uq_employee_meet_absence_date UNIQUE (employee_id, meet_id, absence_id, date_id),

    CONSTRAINT fk_timesheet_employees FOREIGN KEY (employee_id) REFERENCES dim_employees(employee_id),
    CONSTRAINT fk_timesheet_meetings FOREIGN KEY (meet_id) REFERENCES dim_meetings(meet_id),
    CONSTRAINT fk_timesheet_absences FOREIGN KEY (absence_id) REFERENCES dim_absences(absence_id),
    CONSTRAINT fk_timesheet_dates FOREIGN KEY (date_id) REFERENCES dim_dates(date_id)

);

-- projects table creation:
CREATE TABLE projects (
    project_id VARCHAR2(20) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR2(100) NOT NULL,
    client_name VARCHAR2(100) NOT NULL,
);
-- tasks table creation:
CREATE TABLE tasks (
    taskID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    taskName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (taskID)
);
-- timetypes table creation: (timetypes sunt cele de genu :Regular, OT...)
CREATE TABLE timeTypes (
    timeTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    timeTypeName VARCHAR2(50) UNIQUE NOT NULL,
    PRIMARY KEY (timeTypeID)
);
-- locations table creation:
CREATE TABLE locations (
    locationID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    locationName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (locationID)
);
-- contry for relocation table creation:
CREATE TABLE countries (
    countryID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    countryName VARCHAR2(100) NOT NULL,
    PRIMARY KEY (countryID)
);
-- timesheets table creation:
-- This is the most important table!

CREATE TABLE timesheets (
    timesheetID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employeeID NUMBER NOT NULL,
    projectID VARCHAR2(20) NOT NULL,
    taskID NUMBER NOT NULL,
    timeTypeID NUMBER NOT NULL,
    -- Datele calendaristice de start si sfarsit al pontajului
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    -- ora de start si ora de finish al programului (in format 24h)
    startHour NUMBER(2) NOT NULL CHECK (startHour BETWEEN 0 AND 23), --Check constaing
    endHour NUMBER(2) NOT NULL CHECK (endHour BETWEEN 0 AND 23), --Check constraint 2
    -- cate ore au fost lucrate (generat automat ca diferenta dintre start-end)
    quantity NUMBER(4,2) GENERATED ALWAYS AS (endHour - startHour) VIRTUAL CHECK (quantity >= 0),
    -- campuri optionale (daca este cazul sunt completate, altfel null)
    locationID NUMBER,        -- pentru business trip
    relocatedCountryID NUMBER, -- pentru relocare (just in case)
    publicHolidayFlag CHAR(1) DEFAULT 'N' CHECK (publicHolidayFlag IN ('Y', 'N')), --daca se lucreaza in timpul unei sarbatori
    -- comentarii ale angajatilor in lecatura cu pontajul
    comments VARCHAR2(400),
    -- date semistructurate (JSON) : Aici putem stoca diferite date hidden (clientFeedback, toolsUsed, etc..)
    extraInfo CLOB CHECK (extraInfo IS JSON),   --2*
    --chei Pk si FK
    PRIMARY KEY (timesheetID),
    CONSTRAINT fk_employee FOREIGN KEY (employeeID) REFERENCES employees(employeeID),
    CONSTRAINT fk_project FOREIGN KEY (projectID) REFERENCES projects(projectID),
    CONSTRAINT fk_task FOREIGN KEY (taskID) REFERENCES tasks(taskID),
    CONSTRAINT fk_timeType FOREIGN KEY (timeTypeID) REFERENCES timeTypes(timeTypeID),
    CONSTRAINT fk_location FOREIGN KEY (locationID) REFERENCES locations(locationID),
    CONSTRAINT fk_country FOREIGN KEY (relocatedCountryID) REFERENCES countries(countryID)
);

